name: siri_wave
description: A Flutter package to create beautiful waveforms like in Siri.
version: 0.1.1
repository: https://github.com/halildurmus/siri_wave

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
